"""Chat session persistence port."""

from typing import Protocol

from app.modules.sessions.schemas import Session


class SessionRepository(Protocol):
    async def create(self, session: Session) -> Session: ...

    async def get(self, session_id: str) -> Session | None: ...

    async def list(self, limit: int) -> list[Session]: ...

    async def rename(self, session_id: str, title: str) -> Session | None: ...

    async def touch(self, session_id: str) -> None: ...

    async def delete(self, session_id: str) -> bool: ...

    async def delete_by_agent(self, agent_id: str) -> int: ...
